#!/bin/sh

python -m venv venv/
source venv/bin/activate
pip install -U pip setuptools wheel nox
pip install -U mkdocs mkdocs-material mkautodoc
pip install -U towncrier
pip install -U twine
pip install -r test-requirements.txt
pip install -e tools/cqlshell
pip install -e ".[compression]"
echo remember to \"source venv/bin/activate\" to enter the virtualenv
echo you can run \"deactivate\" to leave the virtualenv
