#!/bin/sh -e

if [ -d 'dist' ] ; then
    :
    #rm -r dist
fi
if [ -d 'site' ] ; then
    rm -r site
fi
if [ -d 'htmlcov' ] ; then
    rm -r htmlcov
fi
if [ -d 'pysandra.egg-info' ] ; then
    rm -r pysandra.egg-info
fi
