#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}mypy pysandra --ignore-missing-imports --disallow-untyped-defs
${PREFIX}autoflake --in-place --recursive pysandra tests setup.py
${PREFIX}black pysandra tests setup.py
${PREFIX}isort --multi-line=3 --trailing-comma --force-grid-wrap=0 --combine-as --line-width 88 --recursive --apply pysandra tests setup.py
${PREFIX}mypy pysandra --ignore-missing-imports --disallow-untyped-defs
