#!/bin/sh -e

export VERSION=`cat pysandra/__about__.py | grep __version__ | sed "s/__version__ = //" | sed "s/'//g"`
export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

scripts/clean

if ! command -v "${PREFIX}twine" &>/dev/null ; then
    echo "Unable to find the 'twine' command."
    echo "Install from PyPI, using '${PREFIX}pip install twine'."
    exit 1
fi

if ! command -v "${PREFIX}wheel" &>/dev/null ; then
    echo "Unable to find the 'wheel' command."
    echo "Install from PyPI, using '${PREFIX}pip install wheel'."
    exit 1
fi

find pysandra -type f -name "*.py[co]" -delete
find pysandra -type d -name __pycache__ -delete

${PREFIX}python setup.py sdist bdist_wheel
${PREFIX}python -msnakefood3 . pysandra  | dot -Tpng  -Gsize=20,8\! -Gdpi=100 > docs/img/pydeps.png
# ${PREFIX}twine upload dist/*
# ${PREFIX}mkdocs gh-deploy

echo "You probably want to also tag the version now:"
echo "git tag -a ${VERSION} -m 'version ${VERSION}'"
echo "git push --tags"

scripts/clean
